spring:
  application:
    name: PopularVote

  r2dbc:
    url: r2dbc:mysql://localhost:3306/popular-vote
    username: root
    password: my-secret-pw

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
          audience:
      client:
        registration:
          internal-client:
            client-id:
            client-secret:
            authorization-grant-type:
            scope:
            client-authentication-method:
            provider:
        provider:
          internal-provider:
            token-uri:
auth0:
  management:
    audience:

roles:
  citizen-role-id:
  read-only-citizen-role-id:
  politician-role-id:

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
        web: DEBUG